# Generated by Django 5.0.6 on 2024-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic', verbose_name='Profile'),
        ),
    ]
